### ISSUE TITLE
Auto ID could be better

### ISSUE THREAD

**Issue by arodland** [markqvist/tncattach#1]
The readme says "Identification beacons will be transmitted if the amount of time since the last identification is greater than the configured interval and there is any data to send." but that doesn't really facilitate following the rules in the US (and probably many other places) where the requirement is "every 10 minutes and at the end of each transmission".

To do it right according to the common interpretation, you should

1) Send an ID if there's outgoing data, and the ID timer is expired or about to expire.
2) Send an ID (even if idle) if the ID timer is about to expire and we've sent data since the last ID.
3) Send an ID on exit (if reasonably possible) if we've sent data since the last ID.

Another way of looking at it: an ID frame should follow within 10 minutes *after* any transmission.

**Comment by markqvist** [comment]
Agreed, that is a better way of doing it. I'll implement it like that.

**Comment by markqvist** [comment]
This is now implemented in the 0.1.5 release :) Thanks for the help!
https://github.com/markqvist/tncattach/releases/tag/0.1.5
