### ISSUE TITLE
Station Identification: Invalid KISS data frame

### ISSUE THREAD

**Issue by iqw1345** [markqvist/tncattach#14]
When configuring tncattach to use station identification, Direwolf spits back:

`Frame length 7 not in allowable range of 15 to 2123.`
`ERROR - Invalid KISS data frame from client app.`

The frame length naturally varies with the length of the station identification. I attempted to see if the frame length is configurable in Direwolf, but I am not seeing any evidence of that. I can remediate this by typing the station identification until the allowable range is met, but I am wondering if this is expected behavior. If any other information is needed, please let me know.

 Thanks in advance.

**Comment by markqvist** [comment]
Don't use issue trackers for questions or support requests.

For some reason, DireWolf doesn't want to accept a data frame smaller than 15 bytes. Unfortunately, it's not something that can be fixed in tncattach, but you may have luck raising the issue in DireWolf itself.

**Comment by wb2osz** [comment]
The minimum possible length of an AX.25 frame (excluding flags and CRC) is 15.
7 for destination address.
7 for source address.
1 for control byte.

Could you explain more about the context?

73,
John WB2OSZ

**Comment by iqw1345** [comment]
Certainly!

With Direwolf running, I'll run tncattach using the example from the manual, but attach my call sign to it. I set the interval extremely low to see the error consistently.

`sudo tncattach -T -H localhost -P 8001 -s "N5RLD" -t 5 --ethernet --mtu 576 --noipv6 --ipv4 10.92.0.10/24`

Direwolf prints out:
`Frame length 5 not in allowable range of 15 to 2123.`
`ERROR - Invalid KISS data frame from client app.`

However, if I run the command like this:
`sudo tncattach -T -H localhost -P 8001 -s "N5RLD N5RLD N5RLD" -t 5 --ethernet --mtu 576 --noipv6 --ipv4 10.92.0.10/24`

Direwolf successfully prints out:
`[0L] (Not AX.25)N5RLD N5RLD N5RLD`

There's no mention of needing to phrase my call sign as above in the manual and someone not paying careful attention might not realize that their callsign was never transmitted. Therefore, I presume that this is not expected behavior.

**Comment by wb2osz** [comment]
Apparently, tncattach is just sticking the characters into the HDLC frame rather then attempting to construct a standard AX.25 frame which everyone would be able to understand.
Adding the debug option "-d k" to the direwolf command line will reveal more clues.

**Comment by iqw1345** [comment]
Apologies for not debugging earlier.

`direwolf -d k`

Did not print any new information for us.

I ran `direwolf -d kn` instead.

Here are those results:

`<<< Data frame from KISS client application, channel 0, total length = 8`
`  000:  c0 00 4e 35 52 4c 44 c0                          ..N5RLD.`
`Frame length 5 not in allowable range of 15 to 2123.`
`ERROR - Invalid KISS data frame from client app.`
