### ISSUE TITLE
Support KISS over TCP

### ISSUE THREAD

**Issue by arodland** [markqvist/tncattach#2]
Direwolf natively supports KISS over TCP (default port 8001). It has a serial port emulation mode (using a PTY) to make kissattach happy, but it's kind of awkward. Soundmodem for Windows also does KISS over TCP. It would be nice to work with this.

**Comment by valentintintin** [comment]
I have just found your project and kiss over TCP with Direwolf is a must have.
It could be nice if you add it inside :)
Thanks a lot :relaxed:

**Comment by markqvist** [comment]
Now implemented in pending release 0.1.8
