### ISSUE TITLE
argp_parse() always crashes on Debian bullseye/sid

### ISSUE THREAD

**Issue by yalla** [markqvist/tncattach#4]
When my rnodes arrived today (thanks for the fast shipping btw!) I had instant success running `tncattach` on FC32, but ran into trouble on my Debian based system.

Example:
```
$ sudo ./tncattach /dev/ttyUSB0 115200 --ethernet --mtu 482 --noipv6 --ipv4 10.92.0.11/24
Usage: tncattach [OPTION...] port baudrate
Try `tncattach --help' or `tncattach --usage' for more information.
```
After much trial and error (and trying to remember how gdb worked again), I found out that `argp_parse()` in line 568 always fails, but only on this one system. It *might* be related to `libc-2.31-0ubuntu9` as there *seem* to be some bugs. Poking around I found one workaround which works for me but might break other things. I suspected `arguments.kiss_over_tcp` not to be initialized correctly; I actually set a breakpoint before that call and stepped, just to realize that `argp_parse` always fails.

So here a patch which works for me.

```
diff --git a/tncattach.c b/tncattach.c
index 30e9a25..f24ed65 100644
--- a/tncattach.c
+++ b/tncattach.c
@@ -564,6 +564,7 @@ int main(int argc, char **argv) {
     arguments.noup = false;
     arguments.id_interval = -1;
     arguments.valid_id = false;
+    arguments.kiss_over_tcp = false;
 
     argp_parse(&argp, argc, argv, 0, 0, &arguments);
 
@@ -631,4 +632,4 @@ int main(int argc, char **argv) {
     read_loop();
 
     return 0;
-}
\ No newline at end of file
+}
```
I don't think it'll break anything else, as `argp_parse()` is supposed to set `kiss_over_tcp` to true if `-T` is given, but, alas, I'm a horrible programmer so bear with me... :-)

**Comment by markqvist** [comment]
Thanks for discovering this and providing the fix. As far as I can tell that's an oversight on my part, and for some reason it didn't break anything before Bullseye. I'm pushing your fix to the repo now, and will prepare a release later today with your fix and the man page included.
